Add PGHOST env variable when migrating database
On a new Ubuntu 16.04 machine, when running `psql`:

```
$ psql -U postgres -l
Error: Invalid data directory
```

This seems to be related to postgresql-common update.  When neither
`PGCLUSTER` nor `PGHOST` is specified, the new `psql` looks for a
cluster called "main" and the old `psql` doesn't have cluster defined.

So defining `PGHOST` fixes the problem.