Run psql commands with PGHOST or as postgres
On fresh ubuntu 16.04 servers (e.g. katalyst01), we have problems
running psql commands as non-root or non-postgres users:

```
karen@katalyst01:~$ psql -U postgres
Error: Invalid data directory
```

There are different ways of getting this to work:

```
karen@katalyst01:~$ sudo -u postgres psql -U postgres
psql (9.4.15)
Type "help" for help.
postgres=# \q
```

```
karen@katalyst01:~$ PGHOST=localhost psql -U postgres
psql (9.4.15)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384,
bits: 256, compression: off)
Type "help" for help.

postgres=#
```

For psql commands that don't require a special user, we use `postgres`
as the user and for commands that are already running as a different
user, we use `PGHOST` method.