Set the correct db url when migrating in copy_database.yml
Instead of using the db settings in `/etc/cnx/publishing/app.ini` for migrating
the database, we need to use the one we just copied.

```
TASK [migrate database] *******************************************************************************************************************************************************************************************
fatal: [staging08.cnx.org]: FAILED! => {"changed": true, "cmd": ["/var/cnx/venvs/publishing/bin/dbmigrator", "--config", "/etc/cnx/archive/app.ini", "--context", "cnx-db", "migrate"], "delta": "0:00:01.453792",
"end": "2018-01-24 11:41:53.236355", "msg": "non-zero return code", "rc": 1, "start": "2018-01-24 11:41:51.782563", "stderr": "Traceback (most recent call last):\n  File \"/var/cnx/venvs/publishing/bin/dbmigrato
r\", line 11, in <module>\n    sys.exit(main())\n  File \"/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/cli.py\", line 116, in main\n    return args['cmmd'](**args)\n  File \"/var/cnx/ve
nvs/publishing/local/lib/python2.7/site-packages/dbmigrator/utils.py\", line 153, in wrapper\n    with db_connect(db_conn_str) as db_conn:\n  File \"/usr/lib/python2.7/contextlib.py\", line 17, in __enter__\n
 return self.gen.next()\n  File \"/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/utils.py\", line 54, in db_connect\n    db_conn = psycopg2.connect(*args, **kwargs)\n  File \"/var/cnx/ven
vs/publishing/local/lib/python2.7/site-packages/psycopg2/__init__.py\", line 130, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File \"/var/cnx/venvs/publishing/local/
lib/python2.7/site-packages/dbmigrator/utils.py\", line 85, in wait_select_inter\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  database \"repository\" does not exist", "stderr_lines": ["Traceback
(most recent call last):", "  File \"/var/cnx/venvs/publishing/bin/dbmigrator\", line 11, in <module>", "    sys.exit(main())", "  File \"/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/cli.py\", line 116, in main", "    return args['cmmd'](**args)", "  File \"/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/utils.py\", line 153, in wrapper", "    with db_connect(db_conn_st$
) as db_conn:", "  File \"/usr/lib/python2.7/contextlib.py\", line 17, in __enter__", "    return self.gen.next()", "  File \"/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/utils.py\", l$
ne 54, in db_connect", "    db_conn = psycopg2.connect(*args, **kwargs)", "  File \"/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/psycopg2/__init__.py\", line 130, in connect", "    conn = _connec$
(dsn, connection_factory=connection_factory, **kwasync)", "  File \"/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/utils.py\", line 85, in wait_select_inter", "    state = conn.poll()", $
psycopg2.OperationalError: FATAL:  database \"repository\" does not exist"], "stdout": "", "stdout_lines": []}
```