Run buildout as root instead of www-data
We're getting permission errors during buildout:

```
OSError: [Errno 13] Permission denied: '/var/cnx/venvs/cnx-buildout/build'
...

error: could not create '/var/cnx/venvs/cnx-buildout/lib/python2.4/site-packages/psycopg2': Permission denied
...
```